services:
  db:
    image: postgres:17.2
    env_file:
      - .envDb
    volumes:
      - formatrack:/var/lib/postgresql/data
  backend:
    platform: linux/amd64
    image: kesopam/formatrackback:1.3
    env_file:
      - .envBack
    depends_on:
      - db
  frontend:
    platform: linux/amd64
    image: kesopam/react-formatrack:1.2
    env_file:
      - .envFront
    ports:
      - "5173:5173"
    depends_on:
      - backend
  doc_tecnica:
    platform: linux/amd64
    image: kesopam/doc-tecnica:1.3
    restart: always
  
  doc_manual:
    platform: linux/amd64
    image: kesopam/manual-usuario:1.2
    restart: always
  nginx:
    image: nginx:alpine
    container_name: formatrack_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - doc_tecnica
      - doc_manual

volumes:
  formatrack:
