services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: formatrackdatabase
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    platform: linux/amd64
    image: luis145/formatrackbackend:1.0
    env_file:
      - ./Back/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    platform: linux/amd64
    image: luis145/formatrackfrontend:1.0
    env_file:
      - ./Front/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

nginx:
    image: nginx:alpine
    container_name: formatrack_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

volumes:
  formatrack:
